

#ifndef JVELOCALIZATIONDEFINES_H
#define JVELOCALIZATIONDEFINES_H


#define JVE_LOCALIZATION_FALLBACK_LOCALE  "en_US"


#define JVE_LOCALIZATION_LOCALE_EN_US  "en_US"
#define JVE_LOCALIZATION_LOCALE_RU_RU  "ru_RU"


#define JVE_LOCALIZATION_QT_TRANSLATIONS_PREFIX  "qt_"
#define JVE_LOCALIZATION_TRANSLATIONS_SUFFIX     ".qm"

#define JVE_LOCALIZATION_CORE_TRANSLATIONS_PREFIX  ":/translations/core/"
#define JVE_LOCALIZATION_GUI_TRANSLATIONS_PREFIX   ":/translations/gui/"


#define JVE_SETTINGS_LOCALIZATION_LOCALE  "locale"


#endif // JVELOCALIZATIONDEFINES_H


