

#ifndef JVEPROJECTSOURCESITEMFILEDEFINES_H
#define JVEPROJECTSOURCESITEMFILEDEFINES_H


#define JVE_PROJECT_SOURCES_ITEM_VIDEO_FILE_EXTENSIONS_LIST "*.mkv *.avi *.mp4"
#define JVE_PROJECT_SOURCES_ITEM_IMAGE_FILE_EXTENSIONS_LIST "*.jpg *.png *.gif"
#define JVE_PROJECT_SOURCES_ITEM_AUDIO_FILE_EXTENSIONS_LIST "*.wav *.mp3 *.ac3"
#define JVE_PROJECT_SOURCES_ITEM_TEXT_FILE_EXTENSIONS_LIST  "*.txt"


#endif // JVEPROJECTSOURCESITEMFILEDEFINES_H


