

#ifndef JVEPROJECTSOURCESFILEEXTENSIONSDEFINES_H
#define JVEPROJECTSOURCESFILEEXTENSIONSDEFINES_H


#define JVE_SOURCES_VIDEO_FILE_EXTENSIONS_LIST "*.mkv *.avi *.mp4"
#define JVE_SOURCES_IMAGE_FILE_EXTENSIONS_LIST "*.jpg *.png *.gif"
#define JVE_SOURCES_AUDIO_FILE_EXTENSIONS_LIST "*.wav *.mp3 *.ac3"
#define JVE_SOURCES_TEXT_FILE_EXTENSIONS_LIST  "*.txt"


#endif // JVEPROJECTSOURCESFILEEXTENSIONSDEFINES_H


