

#ifndef JVEGUIBLACKSTYLEDEFINES_H
#define JVEGUIBLACKSTYLEDEFINES_H


#define JVE_GUI_BLACK_STYLE_TEXT_COLOR           "#888888"
#define JVE_GUI_BLACK_STYLE_DISABLED_TEXT_COLOR  "#202020"

#define JVE_GUI_BLACK_STYLE_BACKGROUND_COLOR            "#000000"
#define JVE_GUI_BLACK_STYLE_SELECTION_BACKGROUND_COLOR  "#131313"

#define JVE_GUI_BLACK_STYLE_BORDER_COLOR  "#202020"


#endif // JVEGUIBLACKSTYLEDEFINES_H


