

#ifndef JVEGUIWINDOWSAPPEARANCEDEFINES_H
#define JVEGUIWINDOWSAPPEARANCEDEFINES_H


#define JVE_GUI_DIALOG_MIN_WIDTH   380 // pixels
#define JVE_GUI_DIALOG_MIN_HEIGHT  180 // pixels


#endif // JVEGUIWINDOWSAPPEARANCEDEFINES_H


