

#ifndef JVEGUIAPPEARANCEDEFINES_H
#define JVEGUIAPPEARANCEDEFINES_H


#define JVE_GUI_MENU_RECENT_MAX_NUMBER  9 // entries


#define JVE_GUI_MARGIN_SIZE       5 // pixels
#define JVE_GUI_BIG_MARGIN_SIZE  10 // pixels


#define JVE_GUI_HORIZONTAL_SPACE     5 // pixels
#define JVE_GUI_VERTICAL_SPACE       5 // pixels
#define JVE_GUI_BIG_VERTICAL_SPACE  10 // pixels


#define JVE_GUI_TOOLS_LAYOUT_SPACING  2 // pixels


#define JVE_GUI_VIDEO_MONITOR_VIEWPORT_MIN_WIDTH   320 // pixels
#define JVE_GUI_VIDEO_MONITOR_VIEWPORT_MIN_HEIGHT  180 // pixels


#define JVE_GUI_SEARCH_WIDGET_MIN_VISIBLE_CHARACTERS  6 // number of characters


#endif // JVEGUIAPPEARANCEDEFINES_H


