

#ifndef JVEGUISETTINGSDEFINES_H
#define JVEGUISETTINGSDEFINES_H


#define JVE_GUI_SETTINGS_RECENT_PROJECTS  "mainMenu/recentProjects"


#define JVE_GUI_SETTINGS_PROJECT_TREE_TRANSPORT_BAR_POSITION  "projectTree/transportBarPosition"
#define JVE_GUI_SETTINGS_PROJECT_TREE_VIEW_SCENE_STATE        "projectTree/viewSceneState"


#endif // JVEGUISETTINGSDEFINES_H


